name: sunghae blog
description: since 2021.08
meta_description: "sunghae blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/sunghaeJoung"
domain_name: "sunghaeJoung.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://sunghaeJoung.github.io/"
author: "sunghaejoung"

# Disqus config
disqus-shortname: ""
