name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "성장하는 개발자 썽로그, since 2021.08"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "sunghaeJoung"
domain_name: "https://sunghaejoung.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://sunghaejoung.github.io/"
author: "sunghaeJoung"

# Disqus config
disqus-shortname: ""
